title: Gentape
description: Endless generative music. Made with <a href="https://github.com/meleyal/gen">Gen.js</a>
baseurl: "/"
markdown: kramdown
collections:
  tapes:
    output: true
defaults:
  - scope:
      path: ""
      type: "tapes"
    values:
      layout: tape
